language: python
python:
    - "3.5"
    - "3.6"

install:
    - python3 setup.py install
    - pip install pytest pytest-cov coveralls

script:
    - py.test -v --cov aiotraversal --cov-report term-missing

after_success:
    - coveralls
